import os
import uvicorn
import re
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Any, Optional

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.tools import QuerySQLDatabaseTool
from langchain_classic.tools.retriever import create_retriever_tool
from langchain_core.messages import HumanMessage, AIMessage
from langchain.agents import create_agent


load_dotenv()
if not os.getenv("OPENAI_API_KEY"):
    print("OPENAI_API_KEY not set. Please set it as an environment variable")
    exit()

print("Initializig core components...")
llm = ChatOpenAI(model='gpt-4o', temperature=0)
embeddings = OpenAIEmbeddings()

db = SQLDatabase.from_uri("sqlite:///retail.db")


try:
    vectorstore = FAISS.load_local(
        "faiss_index",
        embeddings,
        allow_dangerous_deserialization=True
    )
except ImportError:
    print("FAISS is not installed. Run 'pip install faiss-cpu'")
    exit()
except Exception as e:
    print(f"Could not load FAISS index. Did you run 'create_rag_index.py'? Error: {e}")
    exit()
    
retriever = vectorstore.as_retriever()
print("Components initialized successfully.")

schema_retriever_tool = create_retriever_tool(
    retriever,
    "schema_search",
    "Use this tool to find relevent table and column information (schema) in retail.db database before generating a SQL query. Pass a natural language question as the query."
)

sql_query_tool = QuerySQLDatabaseTool(db=db)

tools = [schema_retriever_tool, sql_query_tool]

system_prompt = """
You are 'SQL Query Buddy', an expert data analyst AI. Your goal is to help users get actionable insights from a retail database.

### CRITICAL RULE
You are forbidden from answering any question from your own knowledge. 
Your *only* job is to use tools. Every answer you provide MUST be generated by following the 4-Step Workflow below.
If you cannot use your tools, you MUST state that you cannot access the database.
DO NOT HALLUCINATE OR MAKE UP ANSWERS.

---
### 4-STEP WORKFLOW

You MUST follow this 4-step process for every user request:

1.  **Analyze Context & Retrieve Schema:**
    * First, analyze the full `chat_history` to understand the complete conversational context.
    * Then, use the `schema_search` tool to find the relevant tables, columns, and join keys for the user's specific question. This is mandatory.

2.  **Generate SQL:**
    * Based on the context and the retrieved schema, generate one single, accurate, and efficient SQL query.
    * **CRITICAL:** The database is SQLite. You MUST use SQLite-compatible syntax (e.g., `strftime` for dates, `DATE('now')`).

3.  **Execute Query:**
    * Use the `QuerySQLDataBaseTool` to run the SQL query.

4.  **Format the Answer:**
    * You MUST format your final response as a single, complete message structured with the **exact 4 parts** defined below. Do NOT output your thought process or the 4-step-process itself.

---
### ERROR & EMPTY RESULT HANDLING

* **IF THE SQL QUERY FAILS:** Do NOT just say "I encountered an error."
    1.  Provide the `Explanation`, `SQL` (with the error), and `Raw Results` (with the error message).
    2.  For the `AI-Driven Insight`, explain the error in simple terms (e.g., "The query failed because the column 'name' is ambiguous; it exists in two tables.") and suggest a fix.

* **IF THE QUERY RETURNS 0 RESULTS:**
    1.  Provide the `Explanation`, `SQL`, and `Raw Results` (e.g., "Query returned no results.")
    2.  For the `AI-Driven Insight`, state that the query ran but found no data.
    3.  Provide a likely hypothesis (e.g., "This means there were no sales for this category in the last 30 days.")

---
### RESPONSE FORMAT (MANDATORY)

You MUST structure your response with these 4 parts.

**Explanation:**
(Provide a beginner-friendly explanation of the SQL query)

**SQL:**
```sql
(The generated SQL query)

**Raw Results:**
```
(The raw query results from the tool)
```

**AI-Driven Insight:**
(This is your most important task. 
Provide a concise, human-like insight based on the raw results. 
Interpret the data, don't just repeat it. Identify trends, anomalies, or key takeaways.
If the query fails or is empty, follow the Error Handling rules.)

FOLLOW-UP QUESTION RULE
After your AI-Driven Insight, add exactly one blank line.
Then, naturally continue with one single follow-up question that fits the insight.
Do NOT include any title like "Suggested Follow-Up."
Example: "...This indicates a positive trend.
Would you like me to break this down by product category?"
"""

agent = create_agent(llm, tools, system_prompt=system_prompt)

app = FastAPI(
    title="SQL Query Buddy API",
    description="API for the Codecademy GenAI Bootcamp Contest Project"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

class ChatRequest(BaseModel):
    question: str
    chat_history: Optional[List[Any]] = []
    
class EnhanceRequest(BaseModel):
    prompt: str
    
class ChatResponse(BaseModel):
    answer: str
    chat_history: Optional[List[Any]] = []
    
AFFIRMATION = {
    "yes", "sure", "please do", "go ahead", "okay", "yes please", "yep", "y", "ok"
}
    
@app.post("/enhance-prompt")
async def enhance_prompt(request: EnhanceRequest):
    print(f"Refining prompt: {request.prompt}")
    
    enhance_system_prompt = """
    You are an expert AI Data Analyst assistant. Your specific task is to take a short, vague, or incomplete natural-language query from a user about a **retail database** and rewrite it into a clear, specific, and unambiguous question that a data analysis model can effectively answer.

    **Core Enhancement Rules:**
    1.**Infer Metrics:** If a metric is missing, add the most logical one. (e.g., "top customers" -> "top customers by **total sales revenue**").
    2.**Add Grouping:** If a user asks for a broad metric, add a logical grouping. (e.g.,"product sales" -> "total sales **per product category**").
    3.**Specify Timeframes:** If no timeframe is given, default to a common, relevant one.(e.g., "how are sales?" -> "What is the total sales revenue **for the last 30 days**?").
    4.**Resolve Ambiguity:** Replace vague words like "best" or "popular" with specific metrics. (e.g., "best products" -> "top 10 products by **units sold**").

    Return ONLY the single, enhanced query. Do not include any explanation, preamble, or markdown.

    Example 1:
    User: "top 5 customers"
    Enhanced: "Show me the top 5 customers by total purchase amount for the last 90 days."

    Example 2:
    User: "products sales"
    Enhanced: "What is the total sales revenue per product category for the current month?"

    Example 3:
    User: "how are we doing?"
    Enhanced: "What is the total sales revenue and total number of orders for the last 30 days compared to the previous 30 days?"

    Example 4:
    User: "most popular items"
    Enhanced: "List the top 10 products by total units sold in the last 30 days."
    """
    
    try:
        response = llm.invoke([
            HumanMessage(content=enhance_system_prompt),
            HumanMessage(content=request.prompt)
        ])
        
        enhanced_prompt = response.content
        return {"enhanced_prompt": enhanced_prompt}
    except Exception as e:
        print(f"Error enhancing prompt: {e}")
        return {"enhanced_prompt": request.prompt}
    
@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    print(f"Request received: {request.question}")
    
    user_question = request.question.strip().lower().rstrip(".").rstrip("!")
    original_question = request.question
    
    if user_question in AFFIRMATION and request.chat_history:
        try:
            last_ai_answer = request.chat_history[-1][1]
            
            match = re.search(
                r"(Would you like to .*?\?|Should I .*?\?)",
                last_ai_answer,
                re.IGNORECASE | re.DOTALL
            )
            
            if match:
                extracted_question = match.group(1)
                
                if extracted_question.lower().startswith("would you like to "):
                    extracted_question = extracted_question[18:].strip("?")
                elif extracted_question.lower().startswith("should i "):
                    extracted_question = extracted_question[9:].strip("?")
                    
                print("---Affirmation detected!---")
                print(f"Original question: '{original_question}'")
                print(f"Extracted question: '{extracted_question}'")
                
                request.question = extracted_question
        except Exception as e:
            print(f"Error extracting follow-up: {e}")
            pass
    
    history_messages = []
    for item in request.chat_history:
        if isinstance(item, list) and len(item) == 2:
            human, ai = item
            history_messages.append(HumanMessage(content=human))
            history_messages.append(AIMessage(content=ai))
        
    history_messages.append(HumanMessage(content=request.question))
    
    try:
        response = agent.invoke({
            "messages": history_messages
        })
                
        ai_answer = response["messages"][-1].content
        
        raw_match = re.search(
            r"\*\*Raw Results:\*\*\s*```(?:\w*)?\s*(.*?)```",
            ai_answer,
            re.DOTALL
        )
        
        if raw_match:
            raw_text = raw_match.group(1).strip()
            
            if raw_text.startswith("[") and raw_text.endswith("]"):
                try:
                    parsed = eval(raw_text)
                    if isinstance(parsed, list):
                        formatted = "\n".join(str(row) for row in parsed)
                        ai_answer = ai_answer.replace(raw_text, formatted)
                except Exception:
                    pass
        
        updated_history = (request.chat_history or []) + [[original_question, ai_answer]]
        
        return ChatResponse(answer=ai_answer, chat_history=updated_history)
    
    except Exception as e:
        print(f"Error during agent invocation: {e}")
        return ChatResponse(
            answer=f"Sorry, an error occurred while processing your request: {e}",
            chat_history=request.chat_history
        )
        
@app.get("/")
def root():
    return {"message": "SQL Query Buddy API is running!"}

if __name__ == "__main__":
    print("Starting FastAPI server on http://localhost:8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)